# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push to the repo

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake GIF and SVG
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: lowizetech
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg

      # Check status for debugging
      - name: Check Git Status
        run: git status

      # Push the generated files to the output branch
      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
